# Generated by Django 4.1.7 on 2023-05-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_running_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
