# Generated by Django 4.1.7 on 2023-05-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_connector_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesModel',
            fields=[
                ('connector_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('filetype', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='connector',
            name='files',
        ),
        migrations.AddField(
            model_name='connector',
            name='files',
            field=models.ManyToManyField(to='customer.filesmodel'),
        ),
    ]
